server:
  port: 8787

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          searchPaths: service1,service2
          uri: https://lab.ssafy.com/s07-webmobile3-sub2/S07P12A707.git

        # File based Properties
#        native:
#          searchLocations: file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service1,
#            file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service2

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: jasypt_key